### ISSUE TITLE
Don't offer targets that would do nothing, i.e. adjacent chars

### ISSUE THREAD

**Issue by glucas** [mrkkrp/zzz-to-char#10]
One use case for zapping is to delete the text between delimiters, e.g.

    "|here is a string"

With point at `|` I can zap up to the closing `"`. With `zzz-to-char-up-to-char` it offers both the start and end quotes as possible targets, even though zapping backwards would do nothing here. 

Can you ignore targets adjacent to point?

**Comment by mrkkrp** [comment]
An excellent idea! It should be implemented now.
